# Generated by Django 3.1.4 on 2021-01-03 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backlogs_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlogs',
            name='B_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backlogs_App.student'),
        ),
    ]
