# Generated by Django 3.1.4 on 2021-01-03 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backlogs_App', '0002_auto_20210103_2300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Backlogs',
        ),
    ]
