# Generated by Django 3.1.4 on 2021-01-05 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backlogs_App', '0004_backlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlogs',
            name='B_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Backlogs_App.student'),
        ),
    ]
